/**
 * Custom font categories for FontFinder
 * Use-case based categorization for better user experience
 * 
 * These categories help users find fonts based on their creative intent
 * rather than technical font classifications.
 */

export const CUSTOM_CATEGORIES = {
  // Gaming & Action - Bold, impactful fonts for games and dynamic content
  gaming: [
    "Press Start 2P",
    "Orbitron",
    "Audiowide",
    "Black Ops One",
    "Russo One",
    "Bungee",
    "Bungee Inline",
    "Bungee Shade",
    "Bebas Neue",
    "Teko",
    "Saira Condensed",
    "Quantico",
    "Rajdhani",
    "Electrolize",
    "Exo 2",
    "Kanit",
    "Chakra Petch",
    "Share Tech",
    "Share Tech Mono",
    "Turret Road",
    "Oxanium",
    "Michroma",
    "Jura",
    "Aldrich",
    "Wallpoet",
    "Iceberg",
    "VT323",
    "Silkscreen",
    "Gugi"
  ],

  // Fantasy & Medieval - Mystical, magical, and epic fonts
  fantasy: [
    "Cinzel",
    "Cinzel Decorative",
    "MedievalSharp",
    "Uncial Antiqua",
    "Almendra",
    "Almendra Display",
    "Almendra SC",
    "IM Fell English",
    "IM Fell DW Pica",
    "IM Fell French Canon",
    "UnifrakturMaguntia",
    "Pirata One",
    "Grenze Gotisch",
    "New Rocker",
    "Metal Mania",
    "Rye",
    "Metamorphous",
    "Germania One",
    "Fraunces",
    "Caesar Dressing",
    "Monofett",
    "Nosifer",
    "Butcherman",
    "Eater",
    "Creepster"
  ],

  // Branded & Professional - Clean, corporate, business fonts
  branded: [
    "Montserrat",
    "Poppins",
    "Inter",
    "Work Sans",
    "DM Sans",
    "Lato",
    "Raleway",
    "Rubik",
    "Nunito",
    "Outfit",
    "Plus Jakarta Sans",
    "Manrope",
    "Space Grotesk",
    "Sora",
    "IBM Plex Sans",
    "Red Hat Display",
    "Urbanist",
    "Epilogue",
    "Lexend",
    "Public Sans",
    "Open Sans",
    "Source Sans 3",
    "Roboto",
    "PT Sans",
    "Mukta",
    "Hind",
    "Barlow",
    "Karla",
    "Cabin",
    "Quicksand"
  ],

  // Fun & Playful - Bubbly, casual, comic fonts
  fun: [
    "Fredoka",
    "Bubblegum Sans",
    "Lilita One",
    "Righteous",
    "Pacifico",
    "Comic Neue",
    "Chewy",
    "Londrina Solid",
    "Sigmar One",
    "Baloo 2",
    "Titan One",
    "Shrikhand",
    "Fascinate",
    "Carter One",
    "Boogaloo",
    "Modak",
    "Concert One",
    "Bangers",
    "Luckiest Guy",
    "Bowlby One SC",
    "Caprasimo",
    "Kalam",
    "Bree Serif",
    "Varela Round",
    "Comfortaa",
    "Archivo Black",
    "Creepster",
    "Rammetto One",
    "Karantina"
  ],

  // Elegant & Luxury - Sophisticated, refined, high-end fonts
  elegant: [
    "Playfair Display",
    "Cormorant",
    "Cormorant Garamond",
    "Libre Baskerville",
    "Bodoni Moda",
    "Crimson Text",
    "Crimson Pro",
    "Lora",
    "Merriweather",
    "EB Garamond",
    "Spectral",
    "Vollkorn",
    "Cardo",
    "Unna",
    "Sorts Mill Goudy",
    "Cormorant Infant",
    "Cormorant SC",
    "Cormorant Upright",
    "Castoro",
    "Lusitana",
    "Cinzel",
    "Libre Caslon Text",
    "Petrona",
    "Judson",
    "Gilda Display",
    "Newsreader",
    "Fraunces",
    "Rozha One",
    "Yeseva One"
  ],

  // Retro & Vintage - 70s, 80s, nostalgic vibes
  retro: [
    "Pacifico",
    "Monoton",
    "Shadows Into Light",
    "Permanent Marker",
    "Righteous",
    "Alfa Slab One",
    "Lobster",
    "Lobster Two",
    "Rampart One",
    "Odibee Sans",
    "Fascinate Inline",
    "Eater",
    "Rye",
    "Stalinist One",
    "Creepster",
    "Nosifer",
    "Butcherman",
    "Special Elite",
    "Trade Winds",
    "Vast Shadow",
    "Fascinate",
    "Emblema One",
    "Smokum",
    "New Rocker",
    "Metal Mania",
    "Sancreek",
    "Bungee Shade",
    "Pirata One"
  ],

  // Handwriting & Script - Personal, cursive, calligraphy
  handwriting: [
    "Pacifico",
    "Dancing Script",
    "Shadows Into Light",
    "Permanent Marker",
    "Indie Flower",
    "Satisfy",
    "Kaushan Script",
    "Courgette",
    "Great Vibes",
    "Allura",
    "Tangerine",
    "Alex Brush",
    "Caveat",
    "Amatic SC",
    "Patrick Hand",
    "Homemade Apple",
    "Covered By Your Grace",
    "Gloria Hallelujah",
    "Just Another Hand",
    "Architects Daughter",
    "Sacramento",
    "Yellowtail",
    "Cookie",
    "Pinyon Script",
    "Mr Dafoe",
    "Parisienne",
    "Rochester",
    "Clicker Script",
    "Euphoria Script"
  ],

  // Modern & Minimal - Clean, geometric, contemporary
  modern: [
    "Inter",
    "Roboto",
    "Poppins",
    "Montserrat",
    "Work Sans",
    "DM Sans",
    "Outfit",
    "Space Grotesk",
    "Manrope",
    "Plus Jakarta Sans",
    "Sora",
    "Urbanist",
    "Epilogue",
    "Lexend",
    "Figtree",
    "Hanken Grotesk",
    "Archivo",
    "Titillium Web",
    "Barlow",
    "Open Sans",
    "Ubuntu",
    "Source Sans 3",
    "Nunito",
    "Karla",
    "Quicksand",
    "Heebo",
    "Overpass",
    "Cabin",
    "Hind"
  ],

  // Bold & Impact - Headlines, posters, attention-grabbing
  bold: [
    "Anton",
    "Bebas Neue",
    "Oswald",
    "Bangers",
    "Alfa Slab One",
    "Black Ops One",
    "Titan One",
    "Russo One",
    "Ultra",
    "Passion One",
    "Bungee",
    "Sigmar One",
    "Lilita One",
    "Righteous",
    "Staatliches",
    "Archivo Black",
    "Squada One",
    "Bungee Inline",
    "Fugaz One",
    "Calistoga",
    "Secular One",
    "Monoton",
    "Bowlby One",
    "Hammersmith One",
    "Vast Shadow",
    "Bungee Spice",
    "Abril Fatface",
    "Patua One",
    "Concert One"
  ],

  // Futuristic & Tech - Sci-fi, digital, tech-inspired
  futuristic: [
    "Orbitron",
    "Audiowide",
    "Exo 2",
    "Electrolize",
    "Quantico",
    "Share Tech",
    "Share Tech Mono",
    "Turret Road",
    "Oxanium",
    "Chakra Petch",
    "Saira",
    "Michroma",
    "Gruppo",
    "Iceberg",
    "Jura",
    "Eczar",
    "Aldrich",
    "Wallpoet",
    "Syncopate",
    "Iceland"
  ]
};

// Display names for categories (user-friendly labels)
export const CATEGORY_LABELS = {
  all: "🌐 All Fonts",
  gaming: "🎮 Gaming & Action",
  fantasy: "🧙 Fantasy & Medieval",
  branded: "💼 Branded & Professional",
  fun: "🎨 Fun & Playful",
  elegant: "✨ Elegant & Luxury",
  retro: "📻 Retro & Vintage",
  handwriting: "✍️ Handwriting & Script",
  modern: "🔷 Modern & Minimal",
  bold: "💪 Bold & Impact",
  futuristic: "🚀 Futuristic & Tech"
};
